### ISSUE TITLE
dev branch completely deprecated

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Umikaze#85]
Can we remove the `dev` branch? It holds code no longer used, and based off much older image generation code.

**Comment by Wackerbarth** [comment]
I see no reason to keep it. Since @goeland86 raised the question, I assume that he is also inclined to have that view. So, unless @ThatWileyGuy has reservations, let's drop it.

**Comment by goeland86** [comment]
Yes - it confuses more than it helps at present.

Also the documentation on how to run the install needs to be overhauled, but I'll do that as I find the time.

**Comment by goeland86** [comment]
Better discussion on the topic in https://github.com/intelligent-agent/redeem/issues/170
